employee_analytics:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'employees' # Logical database name
      schema: 'main'
      schemas_and_paths:
        main: '../employees.sqlite' # Relative path to DB file for the 'main' schema
      schema_directory: '..' # Relative path to directory containing DB file(s)