name: 'employee_analytics'
version: '1.0'
config-version: 2

profile: 'employee_analytics'

source-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
    - "logs"

models:
  employee_analytics:
    staging:
      materialized: view
    marts:
      materialized: table